CREATE DATABASE IF NOT EXISTS crud;
USE crud;
CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(225) NOT NULL,
    email VARCHAR(225),
    mobile VARCHAR (15),
    deleted TINYINT DEFAULT 0
);